name: Check Schema

on:
  push: {}
  pull_request:
    branches: [master, "release/*"]

jobs:
  check:
    uses: PyTorchLightning/pytorch-lightning/.github/workflows/_check-schema.yml@ci/define-reusable-workflows
